import type { Content } from "./types";

export const uz: Content = {
  meta: {
    title: "Sifat Buxgalter — MChJ uchun buxgalteriya autsorsingi, Toshkent",
    description:
      "Buxgalteriya va soliq hisobini 2016-yildan ishlayotgan bosh buxgalter yuritadi. Savolga 10 daqiqada javob, hisobotlar muddatida, xatomiz sabab jarima chiqsa — oʻzimiz toʻlaymiz.",
  },
  nav: { services: "Xizmatlar", pricing: "Narxlar", team: "Jamoa", faq: "Savollar", cta: "Uchrashuvga yozilish", langLabel: "Til" },
  hero: {
    kicker: "Buxgalteriya autsorsingi · Toshkent",
    h1: "Buxgalteriyani bizga topshiring — soliq xavfini biz koʻtaramiz",
    sub: "Yillik aylanmasi 1 mlrd soʻmdan ortiq MChJlar uchun toʻliq buxgalteriya va soliq hisobi. Ishni 2016-yildan beri ishlayotgan bosh buxgalter olib boradi: savolga 10 daqiqada javob, hisobotlar muddatida, bizning xatomiz sabab jarima chiqsa — oʻzimiz toʻlaymiz.",
    cta: "Bepul uchrashuvga yozilish",
    ctaAlt: "Telegramda yozish",
    note: "30 daqiqa, Zoom orqali yoki ofisimizda. Hozirgi hisobingizdagi asosiy xavflarni birga koʻrib chiqamiz.",
    sheet: {
      tag: "Namuna",
      title: "Oylik hisobot · sentabr",
      rows: [
        ["QQS deklaratsiyasi", "Topshirildi"],
        ["JShDS va ijtimoiy soliq", "Topshirildi"],
        ["Ish haqi va tabel", "Hisoblandi"],
        ["Kontragentlar tekshiruvi", "Xavf yoʻq"],
        ["Soliqdan talabnomalar", "0"],
      ],
      foot: [
        ["Savolga javob", "10 daqiqagacha"],
        ["Ofisingizga tashrif", "oyiga 3 marta"],
      ],
      stamp: "SIFAT BUXGALTER · TEKSHIRILDI · ",
    },
    facts: [
      ["2016", "yildan buxgalteriyada"],
      ["~20", "kompaniya hisobini yuritgan"],
      ["10 daq.", "savolga javob"],
      ["7 kun", "haftada aloqada"],
    ],
  },
  triggers: {
    kicker: "Qachon murojaat qilishadi",
    h2: "Odatda bizga shu paytda yozishadi",
    items: [
      "Buxgalter ketyapti — dekret, nafaqa yoki boshqa ish — va ishni topshiradigan odam yoʻq",
      "Soliq idorasidan talabnoma yoki tekshiruv dalolatnomasi keldi",
      "Bank hisob raqamingizni blokladi",
      "Buxgalter nima qilayotganini koʻrmaysiz: hisobot bermaydi, savolga kechikib javob beradi",
      "Aylanma oʻsdi, soliq ham oʻsdi — qonuniy kamaytirish yoʻlini hech kim koʻrsatmayapti",
      "Yangi qonunlarni kuzatishga vaqtingiz yoʻq",
    ],
    lead: "Qaysi holat boʻlmasin, ishni bitta qadamdan boshlaymiz — kirish tekshiruvidan.",
  },
  risk: {
    kicker: "Yashirin xavf",
    h2: "Eng qimmat xato hisobotda koʻrinmaydi",
    lead: "Koʻp korxonalarda ombor hisobi Excelda yuritiladi, sotuvning bir qismi rasmiy cheksiz oʻtadi. Birinchi ikki yil hech narsa boʻlmaydi.",
    steps: [
      "Ombor Excelda, sotuvning bir qismi cheksiz",
      "Uchinchi yili tekshiruv keladi va oldingi ikki yilni koʻtaradi",
      "Yashirilgan aylanmaga 20% jarima hisoblanadi",
    ],
    total: "2 000 000 000",
    totalLabel: "soʻm jarima — 10 mlrd soʻm aylanmada",
    answer:
      "Shuning uchun mijozni qabul qilishdan oldin oxirgi davrni tekshiramiz. Javobgarlik bizga oʻtadi — demak, xavfni avval oʻzimiz koʻrishimiz kerak.",
  },
  services: {
    kicker: "Xizmatlar",
    h2: "Buxgalteriyaning hammasi — bitta shartnomada",
    sub: "Roʻyxat shartnomaga kiritiladi. Undan tashqarida nima qolishini birinchi uchrashuvda ochiq aytamiz.",
    groups: [
      {
        title: "Hisob va hisobotlar",
        items: [
          "Toʻliq buxgalteriya va soliq hisobi",
          "Hisobotlarni muddatida topshirish",
          "Debitor va kreditor qarzlar nazorati",
          "Bank operatsiyalari",
          "Hisob-faktura, solishtirma dalolatnoma, ishonchnoma",
        ],
      },
      {
        title: "Soliq",
        items: [
          "Soliqni qonuniy kamaytirish boʻyicha maslahat",
          "Soliq rejimini oʻzgartirish",
          "Soliq xavflarini oldindan aniqlash",
          "Ortiqcha toʻlangan soliqlarni qaytarish",
          "Kontragentlarni tekshirish",
        ],
      },
      {
        title: "Tekshiruv va nizolar",
        items: [
          "Kameral va sayyor tekshiruvlar uchun hujjatlar",
          "Soliq dalolatnomalariga eʼtiroz",
          "Bloklangan hisob raqamini ochish",
          "Yuridik qoʻllab-quvvatlash",
        ],
      },
      {
        title: "Kadrlar va ish haqi",
        items: ["Kadrlar buyruqlari", "Ish haqi va aliment hisob-kitobi", "Mehnat daftarchalari va mehnat shartnomalari"],
      },
      {
        title: "Tashqi savdo",
        items: ["Import va eksport shartnomalarini roʻyxatdan oʻtkazish"],
      },
    ],
  },
  clauses: {
    kicker: "Majburiyatlar",
    h2: "Shartnomaga yozadigan vaʼdalarimiz",
    sub: "Sifat — bizning nomimiz. Uni oʻlchab boʻladigan qilib yozamiz.",
    items: [
      { title: "Javob — 10 daqiqagacha", text: "Siz bilan umumiy Telegram-guruh ochamiz. Haftada 7 kun aloqadamiz, shanba kuni ham." },
      { title: "Xato bizniki — jarima ham bizniki", text: "Bizning aybimiz bilan jarima chiqsa, uni oʻzimiz toʻlaymiz. Shart bitta: ombor hisobi halol yuritilsin." },
      { title: "Soliq optimallashtirish — narx ichida", text: "Soliqni qonuniy kamaytirganimiz uchun foiz olmaymiz. Bozorda bu xizmatga tejalgan summaning 5–10 foizi olinadi." },
      { title: "Buxgalter ofisingizda — oyiga 3 marta", text: "Hujjatlarni joyida koʻramiz, savollaringizga yuzma-yuz javob beramiz." },
      { title: "Maxfiylik — NDA bilan", text: "Soʻrovingiz boʻyicha maxfiylik shartnomasini imzolaymiz. Chet ellik taʼsischisi bor korxonalar uchun ayniqsa muhim." },
      { title: "Faqat litsenziyali dasturlar", text: "1C, Didox, soliq toʻlovchining shaxsiy kabineti — hammasi rasmiy." },
      { title: "Qabuldan oldin — tekshiruv", text: "Oxirgi davrni koʻrmasdan ishni qabul qilmaymiz. Eski xatolarni aniqlaymiz va tuzatish rejasini beramiz." },
    ],
  },
  compare: {
    kicker: "Solishtiring",
    h2: "Buxgalteriya uchun uch yoʻl",
    cols: ["Shtatdagi buxgalter", "Arzon autsorsing", "Sifat Buxgalter"],
    rows: [
      ["Oylik xarajat", "Maosh, soliqlar, ish joyi, dastur", "Oyiga ~1 mln soʻmdan", "Oyiga 5 mln soʻmdan, dasturlar ichida"],
      ["Taʼtil, dekret, ishdan ketish", "Ish toʻxtaydi", "Buxgalter almashadi, tarix yoʻqoladi", "Jamoa ishlaydi, ish toʻxtamaydi"],
      ["Xato uchun jarima", "Siz toʻlaysiz", "Siz toʻlaysiz", "Xato bizniki boʻlsa — biz toʻlaymiz"],
      ["Soliq optimallashtirish", "Buxgalter bilimiga bogʻliq", "Alohida, tejalganning 5–10%", "Narx ichida, 0%"],
      ["Javob tezligi", "Ish vaqtida", "Navbatga qarab", "10 daqiqagacha, haftada 7 kun"],
    ],
  },
  steps: {
    kicker: "Qanday boshlaymiz",
    h2: "Birinchi uchrashuvdan birinchi hisobotgacha",
    items: [
      { title: "Tanishuv", text: "Zoom orqali yoki ofisimizda, 30 daqiqa. Biznesingiz va hozirgi hisob haqida gaplashamiz." },
      { title: "Kirish tekshiruvi", text: "Oxirgi davr hujjatlarini koʻramiz va xavflarni yozma roʻyxat qilib beramiz." },
      { title: "Shartnoma va NDA", text: "Majburiyatlar, narx va xizmatlar roʻyxati — qogʻozda." },
      { title: "Ishni qabul qilish", text: "Oldingi buxgalterdan hujjatlar, 1C bazasi va kirish huquqlarini oʻzimiz olamiz." },
      { title: "Har oy", text: "Hisobotlar muddatida, guruhda oylik hisobot, oyiga 3 marta ofisingizda." },
    ],
  },
  pricing: {
    kicker: "Narxlar",
    h2: "Narx aylanmaga emas, ish hajmiga bogʻliq",
    sub: "Hajm — bu operatsiyalar, xodimlar va hujjatlar soni. Aniq summani kirish tekshiruvidan keyin yozma aytamiz.",
    perMonth: "oyiga",
    featured: "Koʻp tanlanadi",
    plans: [
      {
        name: "Standart",
        price: "5 mln soʻmdan",
        for: "Bitta faoliyat turi, oz sonli xodim",
        items: ["Toʻliq buxgalteriya va soliq hisobi", "Barcha hisobotlar muddatida", "Ish haqi va kadrlar", "Telegram-guruh, 10 daqiqada javob", "Oyiga 3 marta tashrif"],
      },
      {
        name: "Gold",
        price: "Hajmga qarab",
        for: "Import-eksport, ulgurji savdo, bir nechta ombor",
        items: ["Standartdagi hammasi", "Import va eksport shartnomalari", "Kontragentlarni muntazam tekshirish", "Soliq xavflari boʻyicha chorak hisoboti"],
      },
      {
        name: "VIP",
        price: "Hajmga qarab",
        for: "Katta aylanma, chet ellik taʼsischilar",
        items: ["Golddagi hammasi", "Tekshiruv va nizolarda himoya", "Yuridik qoʻllab-quvvatlash", "NDA va alohida bosh buxgalter"],
      },
    ],
    cta: "Hajmni hisoblatish",
    onceTitle: "Bir martalik tekshiruvlar",
    once: [
      { name: "Ekspress-tekshiruv", price: "10 mln soʻmdan", text: "Asosiy soliq xavflarini tez aniqlash" },
      { name: "Bir yillik tekshiruv", price: "70 mln soʻmdan", text: "Butun yil hujjatlari va hisobotlari" },
      { name: "Uch yillik chuqur audit", price: "Kelishiladi", text: "Tekshiruvga tayyorgarlik uchun" },
    ],
    why: {
      h3: "«Nega qimmat?» — eng koʻp beriladigan savol",
      lines: [
        ["Arzon buxgalter, bir yil", "12 mln soʻm"],
        ["Bitta tekshiruv jarimasi, 10 mlrd aylanmada", "2 000 mln soʻm"],
        ["Xatomiz uchun jarima bizda, optimallashtirish foizsiz", "0 soʻm ustama"],
      ],
      result: "Siz buxgalterga emas — xavf yoʻqligiga toʻlaysiz.",
    },
  },
  fit: {
    kicker: "Kim bilan ishlaymiz",
    h2: "Hammani olmaymiz — va bu sizni himoya qiladi",
    yesTitle: "Mos keladi",
    yes: [
      "Yillik aylanmasi 1 mlrd soʻmdan, xodimlari 5 nafardan ortiq MChJ",
      "Import-eksport, ulgurji savdo, turizm, oʻquv markazlari",
      "Toshkent shahri va Toshkent viloyati",
      "Soliqni qonuniy yoʻl bilan kamaytirmoqchi boʻlgan egalar",
    ],
    noTitle: "Olmaymiz",
    no: ["Faqat naqd pulda ishlaydigan biznes", "Alkogol va tamaki", "Naqd pulda ishlaydigan qurilish"],
    note: "Javobgarlikni oʻz boʻynimizga olganimiz uchun faqat halol hisobni qabul qilamiz.",
  },
  team: {
    kicker: "Jamoa",
    h2: "Hisobingizni kim yuritadi",
    people: [
      {
        name: "Ibrohim",
        role: "Bosh buxgalter",
        facts: ["Buxgalteriyada 2016-yildan", "Maishiy texnika kompaniyasi Avangardda bosh buxgalter", "20 ga yaqin kompaniya hisobini yuritgan"],
      },
      {
        name: "Bekzod",
        role: "Mijozlar bilan ishlash",
        facts: ["Birinchi uchrashuv, narx va shartnoma", "Arizaga 1 soat ichida, odatda 10 daqiqada qoʻngʻiroq qiladi", "Telegram: @Davronbekov_Bekzod"],
      },
    ],
  },
  clients: {
    kicker: "Tajriba",
    h2: "Hisobini yuritgan kompaniyalar",
    sub: "Jamoamiz turli yillarda ishlagan korxonalardan bir qismi.",
  },
  faq: {
    kicker: "Savollar",
    h2: "Koʻp soʻraladi",
    items: [
      ["Nega arzon autsorsingdan qimmatroq?", "Narx ichida javobgarlik, tezlik va soliq optimallashtirish bor. Arzon xizmatda jarima xavfi sizda qoladi. Bizda esa xato bizniki boʻlsa, jarimani oʻzimiz toʻlaymiz."],
      ["Oldingi buxgalterning xatolari bilan nima boʻladi?", "Kirish tekshiruvida topamiz va tuzatish rejasini beramiz. Oldingi davr uchun javobgarlikni tekshiruvdan keyin alohida kelishamiz."],
      ["Hujjatlarimiz xavfsizmi?", "Soʻrovingiz boʻyicha NDA imzolaymiz. Faqat litsenziyali 1C va Didoxda ishlaymiz."],
      ["Ofisimizga kelasizlarmi?", "Ha, buxgalter oyiga 3 marta ofisingizga keladi. Uchrashuvlar — ofisimizda yoki Zoomda."],
      ["Dam olish kunlari javob berasizlarmi?", "Ha, haftada 7 kun aloqadamiz. Shanba kunlari ish kuni qisqaroq."],
      ["Toshkentdan tashqarida ishlaysizlarmi?", "Asosan Toshkent shahri va viloyatida — chunki buxgalter oyiga 3 marta ofisingizga boradi."],
    ],
  },
  form: {
    kicker: "Birinchi qadam",
    h2: "Bepul uchrashuvga yoziling",
    sub: "Bekzod 1 soat ichida, odatda 10 daqiqada qoʻngʻiroq qiladi va qulay vaqtni kelishadi.",
    name: "Ismingiz",
    phone: "Telefon",
    company: "Kompaniya nomi (ixtiyoriy)",
    turnover: "Yillik aylanma",
    turnoverOpts: ["1 mlrd soʻmgacha", "1–5 mlrd soʻm", "5–20 mlrd soʻm", "20 mlrd soʻmdan ortiq"],
    submit: "Uchrashuvga yozilish",
    sending: "Yuborilmoqda…",
    ok: "Qabul qildik. Bekzod tez orada qoʻngʻiroq qiladi.",
    err: "Yuborib boʻlmadi. Iltimos, qoʻngʻiroq qiling:",
    invalid: "Ism va telefon raqamini toʻldiring.",
    privacy: "Maʼlumotlaringiz faqat siz bilan bogʻlanish uchun ishlatiladi.",
    orCall: "Yoki hoziroq qoʻngʻiroq qiling",
  },
  footer: {
    addressLabel: "Ofis",
    address: "Toshkent, Yangi Sergeli koʻchasi, 7/2",
    landmark: "Moʻljal: VOLVO binosi",
    mapLink: "Xaritada ochish",
    contacts: "Aloqa",
    hours: "Haftada 7 kun aloqadamiz",
    rights: "Sifat Buxgalter",
  },
};
