import type { Content } from "./types";

export const uz: Content = {
  meta: {
    title: "Sifat Buxgalter — MChJ uchun buxgalteriya autsorsingi, Toshkent",
    description:
      "Buxgalteriya va soliq hisobini 2016-yildan ishlayotgan bosh buxgalter yuritadi. Savolga 10 daqiqada javob, hisobotlar muddatida, xatomiz sabab jarima chiqsa — oʻzimiz toʻlaymiz.",
  },
  nav: { services: "Xizmatlar", faq: "Savollar", cta: "10 daqiqalik qoʻngʻiroq", langLabel: "Til" },
  hero: {
    kicker: "Buxgalteriya autsorsingi · Toshkent",
    h1: "Buxgalteriyani bizga topshiring — soliq xavfini biz koʻtaramiz",
    sub: "Buxgalteringiz, ehtimol, allaqachon bor va hisobotlar vaqtida ketyapti. Biz tadbirkor aslida nima uchun pul toʻlashini qoʻshamiz: 10 daqiqada javob, soliqni qonuniy kamaytirish va javobgarlik — xatomiz sabab jarima chiqsa, oʻzimiz toʻlaymiz. Ishni 2016-yildan beri ishlayotgan bosh buxgalter olib boradi.",
    cta: "Bepul 10 daqiqalik qoʻngʻiroq",
    ctaAlt: "Telegramda yozish",
    note: "Hech qayerga borish shart emas. Bekzod qoʻngʻiroq qilib, hisobingiz haqida bir-ikki savol beradi va asosiy xavf odatda qayerda yashirinishini aytadi.",
    sheet: {
      tag: "Namuna",
      title: "Oylik hisobot · sentabr",
      rows: [
        ["QQS deklaratsiyasi", "Topshirildi"],
        ["JShDS va ijtimoiy soliq", "Topshirildi"],
        ["Ish haqi va tabel", "Hisoblandi"],
        ["Kontragentlar tekshiruvi", "Xavf yoʻq"],
        ["Soliqdan talabnomalar", "0"],
      ],
      foot: [
        ["Savolga javob", "10 daqiqagacha"],
        ["Ofisingizga tashrif", "oyiga 3 marta"],
      ],
      stamp: "SIFAT BUXGALTER · TEKSHIRILDI · ",
    },
    facts: [
      ["2016", "yildan buxgalteriyada"],
      ["~20", "kompaniya hisobini yuritgan"],
      ["10 daq.", "savolga javob"],
      ["7 kun", "haftada aloqada"],
    ],
  },
  triggers: {
    kicker: "Qachon murojaat qilishadi",
    h2: "Odatda hozirgi buxgalter bilan nimadir joyida boʻlmaganda yozishadi",
    items: [
      "Buxgalter ketyapti — dekret, nafaqa yoki boshqa ish — va ishni topshiradigan odam yoʻq",
      "Soliq idorasidan talabnoma yoki tekshiruv dalolatnomasi keldi",
      "Bank hisob raqamingizni blokladi",
      "Buxgalter nima qilayotganini koʻrmaysiz: hisobot bermaydi, savolga kechikib javob beradi",
      "Aylanma oʻsdi, soliq ham oʻsdi — qonuniy kamaytirish yoʻlini hech kim koʻrsatmayapti",
      "Yangi qonunlarni kuzatishga vaqtingiz yoʻq",
    ],
    lead: "Qaysi holat boʻlmasin, ishni bitta qadamdan boshlaymiz — kirish tekshiruvidan.",
  },
  risk: {
    kicker: "Yashirin xavf",
    h2: "Eng qimmat xato hisobotda koʻrinmaydi",
    lead: "Koʻp korxonalarda ombor hisobi Excelda yuritiladi, sotuvning bir qismi rasmiy cheksiz oʻtadi. Birinchi ikki yil hech narsa boʻlmaydi.",
    steps: [
      "Ombor Excelda, sotuvning bir qismi cheksiz",
      "Uchinchi yili tekshiruv keladi va oldingi ikki yilni koʻtaradi",
      "Soliq va jarima qoʻshimcha hisoblanadi — bizning misolda yashirilgan aylanmaning 20%",
    ],
    total: "2 000 000 000",
    totalLabel: "soʻm — hisob-kitob misoli: ikki yilda 10 mlrd soʻm yashirilgan aylanma × 20%",
    answer:
      "Haqiqiy summa qoidabuzarlikka bogʻliq va uni oldindan hisoblash mumkin. Shuning uchun mijozni qabul qilishdan oldin oxirgi davrni tekshiramiz. Javobgarlik bizga oʻtadi — demak, xavfni avval oʻzimiz koʻrishimiz kerak.",
  },
  services: {
    kicker: "Xizmatlar",
    h2: "Buxgalteriyaning hammasi — bitta shartnomada",
    sub: "Roʻyxat shartnomaga kiritiladi. Undan tashqarida nima qolishini birinchi qoʻngʻiroqda ochiq aytamiz.",
    groups: [
      {
        title: "Hisob va hisobotlar",
        items: [
          "Toʻliq buxgalteriya va soliq hisobi",
          "Hisobotlarni muddatida topshirish",
          "Debitor va kreditor qarzlar nazorati",
          "Bank operatsiyalari",
          "Hisob-faktura, solishtirma dalolatnoma, ishonchnoma",
        ],
      },
      {
        title: "Soliq",
        items: [
          "Soliqni qonuniy kamaytirish boʻyicha maslahat",
          "Soliq rejimini oʻzgartirish",
          "Soliq xavflarini oldindan aniqlash",
          "Ortiqcha toʻlangan soliqlarni qaytarish",
          "Kontragentlarni tekshirish",
        ],
      },
      {
        title: "Tekshiruv va nizolar",
        items: [
          "Kameral va sayyor tekshiruvlar uchun hujjatlar",
          "Soliq dalolatnomalariga eʼtiroz",
          "Bloklangan hisob raqamini ochish",
          "Yuridik qoʻllab-quvvatlash",
        ],
      },
      {
        title: "Kadrlar va ish haqi",
        items: ["Kadrlar buyruqlari", "Ish haqi va aliment hisob-kitobi", "Mehnat daftarchalari va mehnat shartnomalari"],
      },
      {
        title: "Tashqi savdo",
        items: ["Import va eksport shartnomalarini roʻyxatdan oʻtkazish"],
      },
    ],
  },
  clauses: {
    kicker: "Majburiyatlar",
    h2: "Shartnomaga yozadigan vaʼdalarimiz",
    sub: "Sifat — bizning nomimiz. Uni oʻlchab boʻladigan qilib yozamiz.",
    items: [
      { title: "Javob — 10 daqiqagacha", text: "Siz bilan umumiy Telegram-guruh ochamiz. Haftada 7 kun aloqadamiz, shanba kuni ham." },
      { title: "Xato bizniki — jarima ham bizniki", text: "Bizning aybimiz bilan jarima chiqsa, uni oʻzimiz toʻlaymiz. Shart bitta: ombor hisobi halol yuritilsin." },
      { title: "Soliq optimallashtirish — foizsiz", text: "Soliqni qonuniy kamaytirish ishimiz ichida. Tejalgan summadan alohida foiz olmaymiz." },
      { title: "Buxgalter ofisingizda — oyiga 3 marta", text: "Hujjatlarni joyida koʻramiz, savollaringizga yuzma-yuz javob beramiz." },
      { title: "Maxfiylik — NDA bilan", text: "Soʻrovingiz boʻyicha maxfiylik shartnomasini imzolaymiz. Chet ellik taʼsischisi bor korxonalar uchun ayniqsa muhim." },
      { title: "Faqat litsenziyali dasturlar", text: "1C, Didox, soliq toʻlovchining shaxsiy kabineti — hammasi rasmiy." },
      { title: "Qabuldan oldin — tekshiruv", text: "Oxirgi davrni koʻrmasdan ishni qabul qilmaymiz. Eski xatolarni aniqlaymiz va tuzatish rejasini beramiz." },
    ],
  },
  compare: {
    kicker: "Solishtiring",
    h2: "Buxgalteringiz allaqachon bor. Mana nima oʻzgaradi",
    sub: "Biz «yana bitta buxgalter» taklif qilmaymiz. Siz aslida nima uchun pul toʻlayotgan boʻlsangiz, oʻshani oʻzgartiramiz: xavf, tezlik va hozir soliqqa ketayotgan pul.",
    cols: ["Hozir, buxgalteringiz bilan", "Sifat Buxgalter bilan"],
    rows: [
      { k: "Javob tezligi", now: "Baʼzan javob bir necha soatdan keyin keladi — bank allaqachon yopilgan", us: "10 daqiqagacha, haftada 7 kun. Shoshilinch toʻlov — 5 daqiqa" },
      { k: "Yangi qonunlar va imtiyozlar", now: "Ular haqida oʻzingiz bilib olasiz — Instagramdan yoki qoʻshningizdan", us: "Birinchi boʻlib aytamiz va 70 ga yaqin imtiyozdan sizga moslarini qoʻllaymiz" },
      { k: "Soliqni qonuniy kamaytirish", now: "Buxgalterning majburiyatiga kirmaydi — odatda hech kim qilmaydi", us: "Ishimiz ichida. Tejalgan summadan alohida foiz olmaymiz" },
      { k: "Siz nimani koʻrasiz", now: "«Hisobot joʻnatildi» — vassalom", us: "Har oy: qancha soliq chiqdi, nega va nimaga tayyorlanish kerak" },
      { k: "Ombor va hujjatlar", now: "Tekshiruv kelmaguncha hech kim solishtirmaydi", us: "Shartnomadan oldin kirish tekshiruvida va keyin har oy solishtiramiz" },
      { k: "Buxgalter xatosi uchun jarima", now: "Kompaniya toʻlaydi", us: "Xato bizniki boʻlsa — jarimani biz toʻlaymiz. Shartnomada yozilgan" },
      { k: "Dekret, pensiya, ishdan ketish", now: "Hisob yarim yoʻlda qoladi, ishni topshiradigan odam yoʻq", us: "Hisob bitta xodimga bogʻliq emas" },
      { k: "Bitta buxgalterda nechta firma", now: "Koʻpincha bir nechta — tekshirishga vaqt yetmaydi", us: "Kam kompaniya olamiz — har birini oxirigacha tekshirish uchun" },
    ],
    note: "Qoʻngʻiroqda omboringiz qanday yuritilishini ayting — birinchi navbatda nimani tekshirish kerakligini aytamiz.",
  },
  benefits: {
    kicker: "Soliq imtiyozlari",
    h2: "70 ga yaqin imtiyozdan qaysilari sizning kompaniyangizga toʻgʻri keladi",
    sub: "Hozircha qoʻngʻiroq qilishga tayyor emasmisiz? Sohangizni tanlang — unga toʻgʻri keladigan imtiyozlarni Telegramga yuboramiz. Qoʻngʻiroqsiz va hech qanday majburiyatsiz.",
    label: "Kompaniyangiz sohasi",
    spheres: ["Import va eksport", "Ulgurji savdo", "Turizm", "Oʻquv markazi", "Ishlab chiqarish", "Xizmatlar", "Boshqa"],
    cta: "Roʻyxatni Telegramda olish",
    note: "70 ga yaqin soliq imtiyozi — bosh buxgalterimiz hisobi. Ularning hammasi ham hammaga toʻgʻri kelmaydi: har bir sohaga oʻzinikilari mos keladi, ayrim sohalarda esa imtiyoz umuman yoʻq — buni ham ochiq aytamiz.",
    message: "Assalomu alaykum! Kompaniyamiz sohasi: {s}. Bizga qaysi soliq imtiyozlari toʻgʻri kelishini yuborib bera olasizmi?",
  },
  fit: {
    kicker: "Kim bilan ishlaymiz",
    h2: "Hammani olmaymiz — va bu sizni himoya qiladi",
    yesTitle: "Mos keladi",
    yes: [
      "Yillik aylanmasi 1 mlrd soʻmdan, xodimlari 5 nafardan ortiq MChJ",
      "Import-eksport, ulgurji savdo, turizm, oʻquv markazlari",
      "Toshkent shahri va Toshkent viloyati",
      "Soliqni qonuniy yoʻl bilan kamaytirmoqchi boʻlgan egalar",
    ],
    noTitle: "Olmaymiz",
    no: ["Faqat naqd pulda ishlaydigan biznes", "Alkogol va tamaki", "Naqd pulda ishlaydigan qurilish"],
    note: "Javobgarlikni oʻz boʻynimizga olganimiz uchun faqat halol hisobni qabul qilamiz.",
  },
  clients: {
    kicker: "Tajriba",
    h2: "Hisobini yuritgan kompaniyalar",
    sub: "Jamoamiz turli yillarda ishlagan korxonalardan bir qismi.",
  },
  faq: {
    kicker: "Savollar",
    h2: "Koʻp soʻraladi",
    items: [
      ["Buxgalterim bor. Nega nimanidir oʻzgartirishim kerak?", "Hisobotni vaqtida topshirish — bu minimum. Biz odatda yoʻq narsani qoʻshamiz: 10 daqiqada javob, soliqni qonuniy kamaytirish, sizga oylik hisobot va bizning xatomiz uchun jarimani oʻzimiz toʻlashimiz."],
      ["Hozirgi buxgalterim bilan nima qilamiz?", "Ishni qabul qilishni oʻz zimmamizga olamiz: siz bilan birga hujjatlar, 1C bazasi va kirish huquqlarini olamiz, kirish tekshiruvida esa nima yopilmay qolganini koʻramiz."],
      ["Oldingi buxgalterning xatolari bilan nima boʻladi?", "Kirish tekshiruvida topamiz va tuzatish rejasini beramiz. Oldingi davr uchun javobgarlikni tekshiruvdan keyin alohida kelishamiz."],
      ["Hujjatlarimiz xavfsizmi?", "Soʻrovingiz boʻyicha NDA imzolaymiz. Faqat litsenziyali 1C va Didoxda ishlaymiz."],
      ["Ofisimizga kelasizlarmi?", "Ha, buxgalter oyiga 3 marta ofisingizga keladi. Uchrashuvlar — ofisimizda yoki Zoomda."],
      ["Dam olish kunlari javob berasizlarmi?", "Ha, haftada 7 kun aloqadamiz. Shanba kunlari ish kuni qisqaroq."],
      ["Toshkentdan tashqarida ishlaysizlarmi?", "Asosan Toshkent shahri va viloyatida — chunki buxgalter oyiga 3 marta ofisingizga boradi."],
    ],
  },
  form: {
    kicker: "Birinchi qadam",
    h2: "Bepul 10 daqiqalik qoʻngʻiroq",
    sub: "Telefoningizni qoldiring — Bekzod 1 soat ichida, odatda 10 daqiqada qoʻngʻiroq qiladi. Hech qayerga borish shart emas: ofisda uchrashuvni faqat oʻzingiz xohlasangiz belgilaymiz.",
    name: "Ismingiz",
    phone: "Telefon",
    company: "Kompaniya nomi (ixtiyoriy)",
    turnover: "Yillik aylanma",
    turnoverOpts: ["1 mlrd soʻmgacha", "1–5 mlrd soʻm", "5–20 mlrd soʻm", "20 mlrd soʻmdan ortiq"],
    submit: "Qoʻngʻiroqni kutaman",
    sending: "Yuborilmoqda…",
    ok: "Qabul qildik. Bekzod tez orada qoʻngʻiroq qiladi.",
    err: "Yuborib boʻlmadi. Iltimos, qoʻngʻiroq qiling:",
    invalid: "Ism va telefon raqamini toʻldiring.",
    privacy: "Maʼlumotlaringiz faqat siz bilan bogʻlanish uchun ishlatiladi.",
    orCall: "Yoki hoziroq qoʻngʻiroq qiling",
    orTelegram: "Yozishmani afzal koʻrasizmi? Bekzodga Telegramda yozing",
  },
  footer: {
    addressLabel: "Ofis",
    address: "Toshkent, Yangi Sergeli koʻchasi, 7/2",
    landmark: "Moʻljal: VOLVO binosi",
    mapLink: "Xaritada ochish",
    contacts: "Aloqa",
    hours: "Haftada 7 kun aloqadamiz",
    rights: "Sifat Buxgalter",
  },
};
