import type { Content } from "./types";

// Oʻzbekcha matn tarjima emas, qayta yozilgan: Toshkentdagi biznes egasi qanday gapirsa, shunday.
// Atamalar: Soliq kodeksining rasmiy oʻzbekcha matni (lex.uz) va mahalliy buxgalteriya firmalari saytlari (01.10.2026).
export const uz: Content = {
  meta: {
    title: "Sifat Buxgalter: MChJ uchun buxgalteriya autsorsingi, Toshkent",
    description:
      "Toshkentdagi MChJlar uchun buxgalteriya va soliq hisobi. Savolingizga 10 daqiqada javob beramiz, hisobotlar oʻz vaqtida topshiriladi, bizning xatomiz bilan jarima chiqsa, oʻzimiz toʻlaymiz.",
  },
  nav: { services: "Xizmatlar", servicesList: "Barcha xizmatlar", faq: "Savollar", contacts: "Aloqa", cta: "10 daqiqalik qoʻngʻiroq", callback: "menga qoʻngʻiroq qiling", menu: "Menyu", langLabel: "Til" },
  hero: {
    factTitle: ["10 daqiqada", "javob"],
    factText: "Kompaniyangiz bilan umumiy Telegram-guruhda, kecha-yu kunduz.",
    h1Muted: "Buxgalteringiz bor.",
    h1: "Lekin soliq boʻyicha xavf baribir sizning zimmangizda.",
    panelTitle: "Bizning xatomiz bilan jarima chiqsa, oʻzimiz toʻlaymiz.",
    panelText: "Hisobotni vaqtida topshirish bu eng kamida qilinadigan ish. Biz bunga yana uchta narsa qoʻshamiz: savolingizga tez javob, soliqni qonuniy yoʻl bilan kamaytirish va shartnomaga yozilgan javobgarlik. Hisobingizni 2016-yildan beri shu sohada ishlayotgan bosh buxgalter oʻzi yuritadi.",
    cta: "Bepul 10 daqiqalik qoʻngʻiroq",
  },
  cases: {
    kicker: "Bizga qachon murojaat qilishadi",
    h2: ["Sizga tanish", "vaziyatlarmi?"],
    lead: "Koʻpincha ikki holatda yozishadi: buxgalter bilan nimadir chatoq boʻlib qolganda yoki hammasi joyidadek tuyulsa-yu, lekin buni hech kim tekshirib koʻrmaganda.",
    items: [
      { title: "Hammasi joyidadek, lekin ortiqcha qancha soliq toʻlayotganingizni hech kim hisoblab koʻrmagan", img: "overpayment", icon: "trend", link: { kind: "services", id: "soliq" }, size: "narrow" },
      { title: "Buxgalter ketyapti: dekretga, pensiyaga yoki boshqa ishga. Ishlarni topshiradigan odam yoʻq", img: "accountant-leaves", icon: "handoff", link: { kind: "articles", id: "prinyat" }, size: "narrow" },
      { title: "Soliqdan talabnoma keldi yoki tekshiruv tayinlandi", img: "tax-request", icon: "clock", link: { kind: "services", id: "tekshiruv" }, size: "tall" },
      { title: "Bank hisob raqamingizni toʻxtatib qoʻydi", img: "account-blocked", icon: "card", link: { kind: "services", id: "blok" }, size: "narrow" },
      { title: "Buxgalter nima qilayotganini bilmaysiz: hisobot bermaydi, javobini soatlab kutasiz", img: "no-transparency", icon: "eye", link: { kind: "services", id: "autsorsing" }, size: "wide" },
      { title: "Aylanma oʻsdi, soliq ham oʻsdi. Qonuniy yoʻl bilan kamroq toʻlashni esa hech kim koʻrsatmayapti", img: "turnover-growth", icon: "percent", link: { kind: "articles", id: "lgoty" }, size: "wide" },
      { title: "Yangi qonunlarni kuzatib borishga vaqtingiz yoʻq", img: "new-laws", icon: "refresh", link: { kind: "services", id: "autsorsing" }, size: "wide" },
    ],
    cta: {
      title: "Qaysi biri boʻlmasin, bitta qadamdan boshlaymiz: ekspress-audit",
      text: "Hisobni qabul qilishdan oldin oxirgi davrni tekshirib chiqamiz. Birinchi 10 daqiqalik qoʻngʻiroq bepul.",
      cta: "Qoʻngʻiroqqa yozilish",
    },
  },
  risk: {
    kicker: "Yashirin xavf",
    h2: "Eng qimmatga tushadigan xato hisobotda koʻrinmaydi",
    lead: "Koʻp korxonalarda ombor Excelda yuritiladi, sotuvning bir qismiga esa chek urilmaydi. Hisobotlarda buni hech kim koʻrmaydi.",
    steps: [
      "Ombor Excelda, sotuvning bir qismi cheksiz",
      "Soliq davr tugaganidan keyin uch yilgacha tekshirishi mumkin (SK 88-modda)",
      "Yashirilgan tushumga soliq hisoblanadi, ustiga 20% jarima (SK 223-modda) va penya qoʻshiladi",
    ],
    calc: {
      title: "Xavfingizni hisoblab koʻring",
      turnover: "Yillik aylanma",
      share: "Cheksiz sotuv ulushi",
      years: "Tekshiruv necha yilni koʻradi",
      bln: "mlrd",
      mln: "mln",
      yearsUnit: ["yil", "yil", "yil"],
      hidden: "Yashirilgan tushum:",
      rows: { fine: "Tushumni yashirgani uchun jarima", vat: "Qoʻshimcha hisoblangan QQS 12%", profit: "Foyda soligʻi 15%", peni: "Kechiktirilgan har kun uchun penya" },
      laws: { fine: "SK 223-modda: yashirilgan tushumning 20%", vat: "SK 258-modda", profit: "SK 337-modda, foyda tushumning 20% boʻlsa", peni: "SK 110-modda: kuniga MB stavkasining (14%) 1/300 qismi" },
      total: "Jami toʻlanadi",
      sum: "soʻm",
      note: "Bu taxminiy hisob, soliq xulosasi emas. Hujjatlaringiz boʻyicha aniq summani ekspress-auditda chiqarib beramiz.",
    },
    answer:
      "Aniq summa qanday qoidabuzarlik boʻlganiga bogʻliq, uni oldindan hisoblab qoʻysa boʻladi. Shuning uchun mijozni olishdan oldin oxirgi davrini tekshiramiz. Javobgarlik bizga oʻtadi, demak xavfni birinchi boʻlib oʻzimiz koʻrishimiz kerak.",
  },
  services: {
    kicker: "Xizmatlar",
    h2: "Butun buxgalteriya bitta shartnomada",
    sub: "Bu roʻyxat shartnomaga kiradi. Nimalar unga kirmasligini birinchi qoʻngʻiroqdayoq ochiq aytamiz.",
    groups: [
      {
        title: "Hisob va hisobotlar",
        items: [
          "Buxgalteriya va soliq hisobini toʻliq yuritish",
          "Hisobotlarni muddatida topshirish",
          "Debitor va kreditor qarzlarni nazorat qilish",
          "Bank operatsiyalari",
          "Elektron hisob-fakturalar, solishtirma dalolatnomalar, ishonchnomalar",
        ],
      },
      {
        title: "Soliqlar",
        items: [
          "Soliqni qonuniy kamaytirish boʻyicha maslahat",
          "Soliq rejimini almashtirish",
          "Soliq xavflarini oldindan topish",
          "Ortiqcha toʻlangan soliqni qaytarib olish",
          "Kontragentlarni tekshirish",
        ],
      },
      {
        title: "Tekshiruv va nizolar",
        items: [
          "Kameral va sayyor tekshiruvlarga hujjat tayyorlash",
          "Soliq dalolatnomasiga eʼtiroz yozish",
          "Toʻxtatilgan hisob raqamini ochtirish",
          "Yuridik yordam",
        ],
      },
      {
        title: "Kadrlar va ish haqi",
        items: ["Kadrlar boʻyicha buyruqlar", "Ish haqi va aliment hisob-kitobi", "Mehnat daftarchalari va mehnat shartnomalari"],
      },
      {
        title: "Tashqi savdo",
        items: ["Import va eksport shartnomalarini roʻyxatdan oʻtkazish"],
      },
    ],
  },
  clauses: {
    chat: {
      title: "Sifat × kompaniyangiz",
      members: "4 aʼzo",
      client: "Direktor",
      us: "Sifat Buxgalter",
      messages: [
        { from: "client", text: "Soliqdan avgust oyi QQS boʻyicha talabnoma keldi. Nima qilamiz?", time: "21:14" },
        { from: "us", text: "Koʻrdik. Yetkazib beruvchining hisob-fakturasida farq chiqqan. Soliqqa javobni ertaga tushgacha tayyorlab qoʻyamiz, sizdan hech narsa kerak emas.", time: "21:19" },
        { from: "client", text: "Rahmat, tushunarli", time: "21:20" },
      ],
      typing: "yozmoqda…",
      gap: "5 daqiqa",
      caption: "Mijoz bilan umumiy guruh shunaqa koʻrinadi. Yozishma namuna sifatida, ismlar yashirilgan.",
    },
    kicker: "Majburiyatlar",
    h2: "Shartnomaga nimalarni yozib qoʻyamiz",
    sub: "«Sifat» degani sifat. Uni shartnomaga oʻlchasa boʻladigan raqamlar bilan yozamiz.",
    items: [
      { title: "10 daqiqada javob", text: "Siz bilan umumiy Telegram-guruh ochamiz: yozdingizmi, 10 daqiqa ichida javob olasiz. Kecha-yu kunduz, shanba-yakshanba ham aloqadamiz." },
      { title: "Xato bizdan boʻlsa, jarima ham bizdan", text: "Bizning aybimiz bilan jarima chiqsa, oʻzimiz toʻlaymiz. Bitta shartimiz bor: ombor halol yuritilsin." },
      { title: "Soliq optimallashtirish uchun foiz olmaymiz", text: "Soliqni qonuniy kamaytirish ishimizning bir qismi. Tejalgan puldan alohida foiz soʻramaymiz." },
      { title: "Buxgalter oyiga 3 marta oʻzi keladi", text: "Hujjatlarni joyida koʻramiz, savollaringizga yuzma-yuz javob beramiz." },
      { title: "Maxfiylik NDA bilan", text: "Soʻrasangiz, maxfiylik shartnomasini imzolaymiz. Taʼsischisi chet ellik boʻlgan korxonalar uchun bu ayniqsa muhim." },
      { title: "Litsenziyali dasturlar, himoyalangan kompyuterlar", text: "1C va soliq toʻlovchining shaxsiy kabineti rasmiy. Kompyuterlarda litsenziyali antivirus turibdi, maʼlumotlaringiz tashqariga chiqmaydi." },
      { title: "Ishni olishdan oldin ekspress-audit", text: "Oxirgi davrni tekshirmasdan turib ishni qabul qilmaymiz. Eski xatolarni topib, ularni qanday tuzatishni rejalab beramiz." },
    ],
  },
  compare: {
    kicker: "Solishtiring",
    h2: "Buxgalteringiz bor. Biz bilan nima oʻzgaradi",
    sub: "Biz «yana bitta buxgalter» emasmiz. Aslida nima uchun pul toʻlayotgan boʻlsangiz, oʻsha narsani oʻzgartiramiz: xavfni, tezlikni va hozir soliqqa ketayotgan pulni.",
    cols: ["Hozir, buxgalteringiz bilan", "Sifat Buxgalter bilan"],
    rows: [
      { k: "Javob qancha vaqtda keladi", now: "Baʼzan bir necha soatdan keyin. Bu orada bank yopilib boʻladi", us: "10 daqiqagacha, kecha-yu kunduz. Shoshilinch toʻlov boʻlsa, 5 daqiqa" },
      { k: "Yangi qonunlar va imtiyozlar", now: "Ular haqida oʻzingiz eshitasiz: Instagramdan yoki tanishlardan", us: "Birinchi boʻlib xabar beramiz va sizga nima taʼsir qilishini tushuntiramiz" },
      { k: "Soliqni qonuniy kamaytirish", now: "Buxgalterning vazifasiga kirmaydi, odatda bilan hech kim shugʻullanmaydi", us: "Ishimizning bir qismi. Tejalgan puldan alohida foiz olmaymiz" },
      { k: "Siz nimani koʻrasiz", now: "«Hisobot topshirildi», boshqa hech narsa", us: "Har oy: qancha soliq chiqdi, nima uchun va nimaga tayyorlanish kerak" },
      { k: "Ombor va hujjatlar", now: "Tekshiruv kelmaguncha hech kim solishtirmaydi", us: "Shartnomadan oldin ekspress-auditda, keyin har oy solishtiramiz" },
      { k: "Buxgalter xatosi uchun jarima", now: "Kompaniya toʻlaydi", us: "Xato bizdan boʻlsa, jarimani oʻzimiz toʻlaymiz. Shartnomada yozilgan" },
      { k: "Dekret, pensiya, ishdan ketish", now: "Hisob yarim yoʻlda qoladi, ishlarni topshiradigan odam yoʻq", us: "Hisob bitta odamga bogʻlanib qolmaydi" },
      { k: "Bitta buxgalterda nechta firma", now: "Koʻpincha bir nechta, tekshirishga vaqti yetmaydi", us: "Kam kompaniya olamiz, har birini oxirigacha tekshirishga vaqtimiz boʻlsin deb" },
    ],
    note: "Qoʻngʻiroqda omboringiz qanday yuritilishini aytib bering, birinchi navbatda nimani tekshirish kerakligini aytamiz.",
  },
  benefits: {
    kicker: "Soliq imtiyozlari",
    h2: "70 ga yaqin soliq imtiyozi bor. Mana beshtasi",
    sub: "Har birining yonida Soliq kodeksidagi moddasi. Sohangizga mos qolgan 65 ga yaqinini Telegramga yuborib beramiz, qoʻngʻiroq qilmasdan, hech qanday majburiyatsiz.",
    sampleTitle: "Roʻyxatdan beshta imtiyoz",
    cols: ["Imtiyoz", "SK moddasi", "Kim uchun"],
    sample: [
      { what: "Tovar eksportida QQS 0%", law: "260-modda", who: "Eksport" },
      { what: "Taʼlim xizmatlari QQSdan ozod", law: "243-modda, 10-band", who: "Oʻquv markazlari" },
      { what: "Ijtimoiy sohada foyda soligʻi 0%", law: "337-modda, 4-band; 59-modda", who: "Taʼlim, litsenziyali tibbiyot, sport" },
      { what: "Investitsiya chegirmasi: yangi uskuna narxining 20%", law: "308-modda", who: "Ishlab chiqarish" },
      { what: "Oʻzbekistonda analogi yoʻq texnologik uskunani QQSsiz olib kirish (roʻyxat boʻyicha)", law: "246-modda, 6-band", who: "Ishlab chiqarish, import" },
    ],
    restTitle: "Sohangizga mos qolgan 65 ga yaqini",
    label: "Kompaniyangiz qaysi sohada",
    spheres: ["Import va eksport", "Ulgurji savdo", "Turizm", "Oʻquv markazi", "Ishlab chiqarish", "Xizmat koʻrsatish", "Boshqa"],
    cta: "Roʻyxatni Telegramda olish",
    note: "70 ga yaqin imtiyozni bosh buxgalterimiz sanab chiqqan. Har birining oʻz shartlari bor, shuning uchun sizga toʻgʻri kelish-kelmasligini hujjatlaringizga qarab tekshiramiz. Baʼzi sohalarda imtiyoz umuman yoʻq, unda ham ochiq aytamiz.",
    message: "Assalomu alaykum! Kompaniyamiz sohasi: {s}. Bizga qaysi soliq imtiyozlari toʻgʻri kelishini yuborib bera olasizmi?",
  },
  fit: {
    kicker: "Kim bilan ishlaymiz",
    h2: "Hammani ham olavermaymiz. Bu sizni himoya qiladi",
    yesTitle: "Biz bilan ishlaydi",
    yes: [
      "Yillik aylanmasi 5 mlrd soʻmdan, xodimlari 5 nafardan koʻp MChJlar",
      "Ishlab chiqarish, xizmat koʻrsatish, ulgurji savdo, import va eksport, marketpleyslar",
      "Toshkent shahri va Toshkent viloyati",
      "Soliqni qonuniy yoʻl bilan kamaytirmoqchi boʻlgan egalar",
    ],
    noTitle: "Olmaymiz",
    no: ["Chakana savdo", "Soliq toʻlashni xohlamaydiganlar", "Hujjatsiz material olib, naqd pulga qilinadigan qurilish", "Alkogol va tamaki"],
    note: "Javobgarlikni oʻz zimmamizga olganimiz uchun faqat halol yuritilgan hisobni qabul qilamiz.",
  },
  clients: { label: "Hisobini bizga ishonib topshirgan kompaniyalar" },
  price: {
    kicker: "Narx",
    h2: "Narx aylanmaga emas, ish hajmiga qarab",
    sub: "Tayyor tariflarimiz yoʻq va bu ataylab. Aylanmasi 25 mlrd, mijozi 4 ta boʻlgan firma aylanmasi 5 mlrd, lekin mijozi 1000 ta boʻlgan firmadan arzonga tushishi mumkin. Narxni aylanma emas, hujjatlar soni belgilaydi.",
    items: [
      { title: "Nimaga qarab hisoblanadi", text: "Kiruvchi va chiquvchi hujjatlar, xoʻjalik operatsiyalari, oylik hisobotlar, kadrlar hujjatlari va xodimlar soniga qarab. Bulardan buxgalterning vaqti kelib chiqadi, vaqtdan esa narx." },
      { title: "Nima boʻlmaydi", text: "Tejalgan soliqdan foiz olmaymiz. Yashirin toʻlovlar yoʻq: shartnomada nima yozilgan boʻlsa, shuni toʻlaysiz." },
      { title: "Nega shtatdagi buxgalterdan qimmat", text: "Shtatdagi buxgalter koʻpincha yon tomondan yana bir nechta firmani yuritadi. Biz kam kompaniya olamiz va har birini oxirigacha tekshiramiz. Siz aynan shu vaqt uchun toʻlaysiz." },
      { title: "Aniq narxni qachon aytasiz", text: "Birinchi qoʻngʻiroqda, hujjatlaringiz hajmini bilganimizdan keyin. Shartnoma tuzilguncha narx oʻzgarmaydi." },
    ],
    cta: "Narxni qoʻngʻiroqda bilib olish",
  },
  expert: {
    kicker: "Tajriba",
    h2: "Bu ishni ichidan bilamiz",
    name: "Ibrohim",
    role: "Sifat Buxgalter bosh buxgalteri",
    bio: "2016-yildan beri buxgalteriyada. Hozir maishiy texnika kompaniyasida bosh buxgalter, shu yillarda 20 ga yaqin kompaniyaning hisobini yuritgan. Sifat mijozlarining hisobini shaxsan oʻzi tekshiradi.",
    stats: [
      { value: "2016", label: "yildan beri buxgalteriyada" },
      { value: "4", unit: "mlrd", label: "soʻm bir yilda tejaldi: mijozdagi eng katta natija" },
      { value: "1", unit: "mlrd", label: "soʻmlik soliq xavfi bir yilda yopildi: eng kattasi" },
      { value: "10 000", label: "ta ombor pozitsiyasi: integratsiya bilan yuritgan eng katta hisob" },
    ],
  },
  reviews: {
    kicker: "Fikrlar",
    h2: "Mijozlarimiz oʻzlari aytib beradi",
    lead: "Uchta qisqa video: bizgacha qanday edi va nima oʻzgardi.",
    label: "Mijoz fikri",
    soon: "Video tez orada",
    play: "Videoni koʻrish",
  },
  steps: {
    h2: ["Arizadan birinchi hisobotgacha", "5 ta qadam"],
    lead: "Uzoq muzokaralar yoʻq: har bir qadamda nima boʻlishi va sizga nima berilishi aniq.",
    items: [
      { title: "10 daqiqalik qoʻngʻiroq", text: "10 daqiqa ichida qoʻngʻiroq qilamiz. Uchta savol beramiz, xavf qayerdaligi shu yerning oʻzida koʻrinadi." },
      { title: "Ekspress-audit", text: "Oxirgi davrlardagi hisobotlar, soliqlar va asosiy hujjatlarni koʻrib chiqamiz." },
      { title: "Natija va narx", text: "Topilgan xavflar va ortiqcha toʻlovlarni koʻrsatamiz, aniq narxni aytamiz." },
      { title: "Shartnoma va ishlarni qabul qilish", text: "NDA va shartnomani imzolaymiz, hujjatlar va 1C bazasini qabul qilib olamiz." },
      { title: "Har oy", text: "Hisobotlar vaqtida topshiriladi, soliqlar hisoblanadi, direktor uchun hisobot qoʻlingizda boʻladi." },
    ],
  },
  report: {
    kicker: "Har oy",
    h2: "Direktor uchun bir sahifalik hisobot",
    lead: "Shunchaki «hisobot yuborildi» emas: nima topshirildi, nima tekshirildi va qancha tejaldi, hammasi koʻrinib turadi. Namunasi mana bunday.",
    title: "Direktor uchun oylik hisobot",
    month: "Avgust 2026",
    badge: "Namuna",
    rows: [
      ["QQS, JShDS, ijtimoiy soliq", "Topshirildi · avg"],
      ["Ombor va 1C solishtiruvi", "Farq yoʻq"],
      ["Kontragentlar tekshiruvi", "31 ta · xavf yoʻq"],
      ["Qoʻllangan imtiyoz", "1 ta · 4,2 mln tejaldi"],
      ["Soliq tekshiruvlari", "0"],
    ],
    footer: "Bosh buxgalter tekshirdi",
  },
  faq: {
    kicker: "Savollar",
    h2: "Koʻp beriladigan savollar",
    items: [
      ["Buxgalterim bor. Nega nimanidir oʻzgartirishim kerak?", "Hisobotni vaqtida topshirish bu eng kamida qilinadigan ish. Biz odatda boʻlmaydigan narsalarni qoʻshamiz: 10 daqiqada javob, soliqni qonuniy kamaytirish, sizga oylik hisobot va bizning xatomiz uchun jarimani oʻzimiz toʻlashimiz."],
      ["Hozirgi buxgalterim bilan nima qilamiz?", "Ishlarni qabul qilishni oʻzimiz olib boramiz: siz bilan birga hujjatlar, 1C bazasi va parollarni olamiz, ekspress-auditda esa nimalar yopilmay qolganini koʻramiz."],
      ["Oldingi buxgalterning xatolari nima boʻladi?", "Ekspress-auditda topamiz va tuzatish rejasini beramiz. Oldingi davr uchun javobgarlikni tekshiruvdan keyin alohida kelishib olamiz."],
      ["Hujjatlarimiz xavfsiz boʻladimi?", "Soʻrasangiz, NDA imzolaymiz. Litsenziyali 1C da ishlaymiz, kompyuterlarda litsenziyali antivirus turibdi."],
      ["Ofisimizga kelasizlarmi?", "Ha, buxgalter oyiga 3 marta ofisingizga keladi. Uchrashuvni bizning ofisda yoki Zoomda ham oʻtkazsa boʻladi."],
      ["Dam olish kunlari ham javob berasizlarmi?", "Ha, kecha-yu kunduz aloqadamiz, shanba va yakshanba ham."],
      ["Toshkentdan tashqarida ishlaysizlarmi?", "Asosan Toshkent shahri va viloyatida, chunki buxgalter oyiga 3 marta ofisingizga borishi kerak."],
    ],
  },
  form: {
    kicker: "Birinchi qadam",
    h2: "Bepul 10 daqiqalik qoʻngʻiroq",
    sub: "Telefon raqamingizni qoldiring, Bekzod 10 daqiqa ichida bogʻlanadi. Hech qayerga borishingiz shart emas: ofisda uchrashuvni faqat oʻzingiz xohlasangiz belgilaymiz.",
    name: "Ismingiz",
    phone: "Telefon",
    company: "Kompaniya nomi (shart emas)",
    turnover: "Yillik aylanma",
    turnoverOpts: ["1 mlrd soʻmgacha", "1–5 mlrd soʻm", "5–20 mlrd soʻm", "20 mlrd soʻmdan koʻp"],
    submit: "Qoʻngʻiroqni kutaman",
    sending: "Yuborilmoqda…",
    ok: "Arizangizni oldik. Bekzod tez orada qoʻngʻiroq qiladi.",
    err: "Yuborib boʻlmadi. Iltimos, oʻzingiz qoʻngʻiroq qiling:",
    invalid: "Ismingiz va telefon raqamingizni yozing.",
    privacy: "Maʼlumotlaringizdan faqat siz bilan bogʻlanish uchun foydalanamiz.",
    orCall: "Yoki hoziroq qoʻngʻiroq qiling",
    orTelegram: "Yozishgan qulayroqmi? Bekzodga Telegramda yozing",
  },
  footer: {
    visit: "Bizning oldimizga kelishingiz shart emas: buxgalter oyiga 3 marta oʻzi keladi. Ofisimizga esa xohlasangiz kelasiz.",
    addressLabel: "Ofis",
    address: "Toshkent, Yakkasaroy tumani, Muqimiy koʻchasi",
    landmark: "",
    mapLink: "Xaritada ochish",
    contacts: "Aloqa",
    hours: "Kecha-yu kunduz aloqadamiz",
    rights: "Sifat Buxgalter",
  },
};
